version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: meetu-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - meetu-network

  app:
    build: .
    container_name: meetu-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/meetu
      - JWT_SECRET=your_jwt_secret_here
      - TENCENT_SECRET_ID=${TENCENT_SECRET_ID}
      - TENCENT_SECRET_KEY=${TENCENT_SECRET_KEY}
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - meetu-network

networks:
  meetu-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
